CREATE TABLE IF NOT EXISTS frozen_item
(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  quantity INT,
  frozen_at DATE
);

CREATE SEQUENCE frozen_item_seq
START WITH 1
INCREMENT BY 50
MINVALUE 0
MAXVALUE 999999999
CYCLE;
