name: Java CI with Maven2

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove H2-database for build
        run: rm data/* -f
      - name: Check
        run: ls -al
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        env:
          TEST_SECRET: 'github-action-step'
        run: mvn -B clean package --file pom.xml
        
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: rara69/freezer-inventory-be
          tags: test
          registry: docker.io
          dockerfile: Dockerfile.local_h2
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
